'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Obras
    Public Property Id As Integer
    Public Property Nome As String
    Public Property Descricao As String
    Public Property Endereco As String
    Public Property DataInicio As Date
    Public Property Responsavel As String
    Public Property Status As String
    Public Property ClienteId As Nullable(Of Integer)

End Class
